name: R Linting
on:
  pull_request:
    paths:
      - '**.R'
  push:
    paths:
      - '**.R'

jobs:
  lint-and-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set R_LIBS_USER
        run: echo "R_LIBS_USER=$(Rscript -e 'cat(.libPaths()[1])')" >> $GITHUB_ENV

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/*.lock') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Install lintr
        run: |
          Rscript -e "install.packages('lintr', repos='https://cran.r-project.org')"

      - name: Get changed R files
        id: changed_r_files
        run: |
          git fetch origin ${{ github.base_ref }}
          git diff --name-only origin/${{ github.base_ref }}...${{ github.sha }} -- '*.R' > changed_r_files.txt

      - name: Annotate lintr warnings
        run: Rscript .github/run_linters.R changed_r_files.txt
